### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by fossfreedom** [asermax/lastfm_queue#1]
I get a segmentation fault with this plugin activated and having played a lastfm song from "my recommendations"

I've traced this down to this section of code where I've added some print statements:

```
def find_track(self, artist, title):
    print "find_track"
    query_model = RB.RhythmDBQueryModel.new_empty(self.db)
    print "query"
    query = GLib.PtrArray()
    print "ptrarray"
    print query
    print artist
    self.db.query_append_params( query, 
                 RB.RhythmDBQueryType.EQUALS, 
                 RB.RhythmDBPropType.ARTIST, artist )
    print "first append"
    self.db.query_append_params( query, 
                  RB.RhythmDBQueryType.EQUALS, 
                  RB.RhythmDBPropType.TITLE, title)     
    print "second append"
```

The trace output is:

(21:32:00) [0x8945ca0] [LastFmQueuePlugin.find_track] lastfm_queue.py:355: find_track
(21:32:00) [0x8945ca0] [LastFmQueuePlugin.find_track] lastfm_queue.py:357: query
(21:32:00) [0x8945ca0] [LastFmQueuePlugin.find_track] lastfm_queue.py:359: ptrarray
(21:32:00) [0x8945ca0] [LastFmQueuePlugin.find_track] lastfm_queue.py:360: `<GPtrArray at 0x9b68a88>`
(21:32:00) [0x8945ca0] [LastFmQueuePlugin.find_track] lastfm_queue.py:361: Yvonne Elliman

Any ideas on how to debug further?

**Comment by asermax** [comment]
I can't tell you for sure, but given that the parameters of the call seems correct (from your traceback), I would say it's an upstream bug on the RhythmDB component.
The only thing I can think you can do, is keep testing it against other tracks from other sources, if the same behavior occurs in some other context, it may help us solve this issue.

I didn't write this plugin myself, just ported it to the 2.x plugin system, so there're some details I'm not completely familiar with; I'll keep looking on the code to see if I can find what could be causing the seg fault.

Thanks for the report!

EDIT: just tested it with the LastFM source and it seems to be buggy; sometimes works, other freezes and sometimes it seg faults like you said. I have no idea what could be causing this behavior. My best bet is a bug on the RhythmDB as I said above.

**Comment by fossfreedom** [comment]
damn - I cant get this plugin to work at all with lastfm recommendations and it randomly crashes with other sources as well.  

Just wondering if the `query = GLib.PtrArray()` is the actual issue here?

the first param is of type RhythmDBQuery - my python is not familiar enough in this area - can you define a new RhythmDBQuery instead of using GLib.PtrArray() ?

**Comment by asermax** [comment]
If you read the Rhytmbox reference for the RhythmDB module (http://developer.gnome.org/rhythmbox/unstable/RhythmDB.html), the RhyhtmboxDBQuery is just a typedef over GPtrArray. In other words, it's just an alias.

For me it's working fine when playing songs from my local music library, I select a song and my queue starts getting dinamically filled with other songs from my local library.

I think you might be confusing how the plugin is used; the plugin was original designed to work with rhythmbox local music library, using last.fm just to ask for recommendations, and if some of the recommended songs are in your library, add it to your playing queue. That way, the queue keeps growing, since each track played brings up more recommendations and so on.

If you have problems using the plugin on your local library, then there's a real issue. Otherwise, it may be some kind of incompatibility between plugins or a sneaky bug, but in that case it doesn't cripple the functionallity (I might disable the plugin when the song source is other than local).

Please let me know if you find out something else about the issue.

**Comment by fossfreedom** [comment]
ok - gptrarray it is then.

I've disabled every plugin except for this one.  Some songs play fine from my local library - others just seg-fault crash rhythmbox :(

Looks like any artist I've never used on lastfm only returns one results - so no issues e.g.

```
  <?xml version="1.0" encoding="utf-8"?>
  <lfm status="ok"> 
  <similartracks track="I Can't Go For That (No Can Do) (HOAX Remix)" artist="Hall &amp; Oates">
  </similartracks></lfm>
```

Whereas if I've played some artist previously on lastfm I regularly get a crash - in these cases lastfm sends back lots and lots of results (XML too large to publish here)

Obviously looking at the first trace and the code - since there is no `<track>` in the XML - nothing to search for in my local library.

Ok, first I thought that may be the query_append_params is not the correct way to do queries any more (speculation) - 

http://developer.gnome.org/rhythmbox/unstable/RhythmDBQueryResults.html

This page suggest perhaps the "RhythmDBQueryResults" functions should be used - but maybe not - further reading suggests the default QueryModel object should have implemented this.  Thus I'm out of ideas.

**Comment by asermax** [comment]
For what I understand about queries (which isn't much, I kinda learned from examples), to make a query against the db, first you build the query using the query_append_params (the db is the responsible for this for some reason), and then you run the RhythmDBQuery against the db, which fills up a RhythmDBQueryResults (as explained in this method http://developer.gnome.org/rhythmbox/unstable/RhythmDB.html#rhythmdb-do-full-query-parsed).

I'm out of ideas too. Since it works fine for me in normal circumstances, it's hard for me to debug the problem.
I'll keep looking in the scenary when using a source other than the local library, since that one I can reproduce in my own machine, and might be able to fix, or in the worse case, deactivate the plugin when using other sources.

If you get more info/results or you find something strange while debugging, let me know too see what we can do.

**Comment by fossfreedom** [comment]
I was looking  through the C documentation and I noticed the "rhythmdb.query_parse" function which returns a GPtrArray.

http://developer.gnome.org/rhythmbox/2.96/RhythmDB.html#rhythmdb-query-parse

Any ideas whether you need to use this function first to "initialise" the query before appending the subquery with query_append_params ?

**Comment by asermax** [comment]
Tried to use it right now, but for some reason that method doesn't figure as a member of the db property on python :S 
I get an error when trying to use it and it isn't listed as a method of shell.props.db ( you can check it out using the Python Console plugin, evaluating 'dir(shell.props.db)' ).

I'm really puzzled about this bug, I seriously have no idea what could be causing it.
Just to be completely sure, you are 100% positive it doesn't work even when playing just a single song from your local library? (After playing that first song with the plugin activated your queue should fill with a couple of song and start "auto feeding" with new recommendations)

**Comment by fossfreedom** [comment]
100% sure - it always segmentation faults at the first query_append_param statement.

In fact - today I download a fresh 12.04 32bit ISO, applied all the updates and git cloned this plugin again.  Same issue - same place in the code :(

Guess this plugin will never work for me. Oh well...

Even tried the webupd8 rhythmbox 2.97 PPA - still the same issue :(

**Comment by asermax** [comment]
I'm really sorry to hear that :/
I'm wondering then, why the hell does it DOES work for me?

If you are still up for it, there is something I think you may test to see if it's a bug on the plugin or it's an upstream bug:
Open the Python Console for Rhythmbox (you have to activate the plugin and then go to 'Tools>Python Console' on the menu), and try issuing some queries against the database:

```
from gi.repository import RB, GLib

db = shell.props.db
query_model = RB.RhythmDBQueryModel.new_empty(db)
query = GLib.PtrArray()

db.query_append_params( query, RB.RhythmDBQueryType.EQUALS, RB.RhythmDBPropType.ARTIST, 'some artist name' )
db.query_append_params( query, RB.RhythmDBQueryType.EQUALS, RB.RhythmDBPropType.TITLE, 'some song name' )   

db.do_full_query_parsed(query_model, query)

for row in query_model:
    print row[0].get_string( RB.RhythmDBPropType.ARTIST )
    print row[0].get_string( RB.RhythmDBPropType.TITLE )

```

**Comment by fossfreedom** [comment]
yep - via interactive - confirmed segmentation fault (core dumped) when copying and pasting the first query_append_params

Repeated this with lastfmqueue disabled as well

running rhythmbox --debug I see the following before the segmentation fault

<pre>
(21:14:16) [0x9d1baa0] [rhythmdb_read_enter] rhythmdb.c:1229: counter: 1
(21:14:16) [0xabb4750] [query_thread_main] rhythmdb.c:4037: entering query thread
(21:14:16) [0xabb4750] [rhythmdb_query_internal] rhythmdb.c:4014: doing query
(21:14:16) [0xabb4750] [do_query_recurse] rhythmdb-tree.c:2305: doing recursive query, 1 conjunctions
(21:14:16) [0xabb4750] [rhythmdb_query_model_add_results] rhythmdb-query-model.c:2248: adding 145 entries
(21:14:16) [0xabb4750] [rhythmdb_query_internal] rhythmdb.c:4020: completed
(21:14:16) [0x9d1baa0] [rhythmdb_read_enter] rhythmdb.c:1229: counter: 2
(21:14:16) [0xabb4750] [query_thread_main] rhythmdb.c:4037: entering query thread
(21:14:16) [0xabb4750] [rhythmdb_query_internal] rhythmdb.c:4014: doing query
(21:14:16) [0xabb4750] [do_query_recurse] rhythmdb-tree.c:2305: doing recursive query, 1 conjunctions
(21:14:16) [0xabb4750] [rhythmdb_query_model_add_results] rhythmdb-query-model.c:2248: adding 0 entries
(21:14:16) [0xabb4750] [rhythmdb_query_internal] rhythmdb.c:4020: completed
(21:14:16) [0x9d1baa0] [idle_process_update] rhythmdb-query-model.c:1187: inserting 145 rows
(21:14:16) [0x9d1baa0] [idle_process_update] rhythmdb-query-model.c:1187: inserting 0 rows
(21:14:16) [0x9d1baa0] [rhythmdb_process_one_event] rhythmdb.c:2537: processing RHYTHMDB_EVENT_QUERY_COMPLETE
(21:14:16) [0x9d1baa0] [rhythmdb_read_leave] rhythmdb.c:1243: counter: 1
(21:14:16) [0x9d1baa0] [rhythmdb_process_one_event] rhythmdb.c:2530: processing RHYTHMDB_EVENT_THREAD_EXITED
(21:14:16) [0x9d1baa0] [rhythmdb_process_one_event] rhythmdb.c:2537: processing RHYTHMDB_EVENT_QUERY_COMPLETE
(21:14:16) [0x9d1baa0] [rhythmdb_read_leave] rhythmdb.c:1243: counter: 0
(21:14:16) [0x9d1baa0] [rhythmdb_process_one_event] rhythmdb.c:2530: processing RHYTHMDB_EVENT_THREAD_EXITED
Segmentation fault (core dumped)
</pre>


Nothing particularly obvious there apart from it knows its querying 145 items which is I think the number of tracks in my test rhythmbox system.

**Comment by asermax** [comment]
In this case, I think it probably haves something to do with the distro or the Rhythmbox version.
Maybe Ubuntu distributes a different (modified) version of rhythmbox, or even glib, that could be causing this error.

**Comment by fossfreedom** [comment]
ok - I've prodded the rhythmbox-dev mailing list and they have advised me to produce a backtrace with the core dump and then file a bugzilla report with the trace.

I'll use your interactive query to produce the crash.

Thanks again.  If any rhythmbox developer looks and comes back at the bug report I'll drop you a comment here.

**Comment by asermax** [comment]
Great! Hope they get to it and find out what's going on there. 

And yes, please let me know if you find something else about this bug, I would love to see this plugin added to your rhythmbox's third party plugins repository :3

**Comment by fossfreedom** [comment]
ok - I havent forgot about this one :)

I've tried both a liveCD of LMDE v13 and Fedora 17

Using your example code above - BOTH give a segmentation fault when you run db.query_append_params.

Deathly silence from my bugzilla report.

I've tried StackOverflow as well (http://stackoverflow.com/questions/12133250/how-do-i-query-for-data-in-rhythmbox) - but apart from a couple of up-votes - no answers...

Thus not really further forward :(

Will continue to look around.

**Comment by asermax** [comment]
LMDE v13? I guess you got that wrong, LMDE doesn't have versions, it's a rolling distro. You probably tried out the standard edition that's based on Ubuntu (which would explain why it fails there too).
But Fredora haves this problem too?? This is REALLY weird. 
If it is of any help, I'm running mine over LMDE pointing at testing (I would say it's practically Debian Testing with a couple of Mint tools, lol). Maybe there's a tiny but critical difference within the libraries on this distros that makes it fail in those :/

Well, hope you find something out; also found your bug on bugzilla, I don't expect them to answer fast (I already filled some bugs and they took a while to look it over), but hopefully they will be able to resolve the issue.

**Comment by fossfreedom** [comment]
yeah - my bad - not v13 - its this live CD I tried - linuxmint-201204-xfce-dvd-32bit.iso - http://www.linuxmint.com/download_lmde.php it says its LMDE.

Its the vanilla Live CD - just installed rhythmbox whilst in live CD mode. N.B. all of this is running in a virtualbox virtual guest - but I doubt that's the issue.

**Comment by asermax** [comment]
Hmmm that it doesn' work on LMDE for you makes it even harder to know where this bug comes from :/ 
The only ideas I got left are:
- It may be architecture related, since I'm using the 64-bit LMDE.
- It may have something to do with Rhythmbox version, since I think testing version is little ahead from the one in the latest LMDE image. But you already tested the latest versions on Ubuntu, so I've little confidence on this one.

**Comment by fossfreedom** [comment]
well would you believe it - yes its a 64bit vs 32bit issue.

It seems 12.04.1 Ubuntu 64bit works just fine with this query whereas the 32bit edition seg faults.

I'm downloading LMDE 64bit - have every confidence this will similarly work.

EDIT - yep - LMDE 64bit works as expected

Ok - lets update buzilla - mailing lists, stackoverflow etc etc.

I'll let the devs figure out whats wrong with 32bit

Suggest close this issue for now.

thanks!
