### ISSUE TITLE
Error displayed when launching rhythmbox

### ISSUE THREAD

**Issue by fossfreedom** [asermax/lastfm_queue#2]
ok - on my newly install 64bit ubuntu ;)

dad@dad-VirtualBox:~$ rhythmbox
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/lastfm_queue/lastfm_queue.py", line 26, in <module>
    import rb
ImportError: No module named rb

(rhythmbox:2173): libpeas-WARNING **: Error loading plugin 'lastfm_queue'

this occurs after activating the plugin, closing rhythmbox and then restarting.

problem goes away with a `Depends=rb` in the plugin file.

Any ideas?

**Comment by asermax** [comment]
That indicates that the plugins loads before the rb plugin is in python's path, so it fails to import it (the plugin uses rb to do asynchronous http calls).
As you said, adding the dependency should fix the problem, loading the plugin only once rb is loaded.
You have any issues after adding the dependency?

**Comment by fossfreedom** [comment]
no - no issues at all - plugin works fine.

This doesnt occur if I've got other plugins activated - only occurs if this is activated on its own.

**Comment by asermax** [comment]
Probably other plugins already have this dependency and load rb before lastfm_queue is loaded.
Well, being that adding the dependency fixes the issue, gonna proceed to close the issue d:

Thanks for the report foss :3
