### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by afrancoto** [asermax/lastfm_queue#5]
When the plugin is active and the button clicked Rhythmbox crashes after a few seconds with this error:

Segmentation error (core dump created)

**Comment by fossfreedom** [comment]
Possibly the same as this issue - #1 ?

i.e. if you are using a 32bit distro - then rhythmbox crashes with python plugins that query for data - this plugin does just that.

N.B. @asermax - suggestion - add this info to the README?

**Comment by asermax** [comment]
Yep, foss is probably right. There is a bug upstream that, in 32bit systems, doesn't allow plugins writen in python to do queries against rhythmbox's database without crashing. 
I'll add a note on the readme as you said foss :+1:

**Comment by afrancoto** [comment]
:( I would have really loved to use this plugin!
