### ISSUE TITLE
[Ubuntu 13.04] Error message at startup

### ISSUE THREAD

**Issue by NicolasEhrhardt** [asermax/lastfm_queue#6]
Hi,

I have an error message when launching rhythmbox. The plugin does nothing when activated. (Ubuntu 13.04 64bit - stock install of rhythmbox)

```
File "/usr/lib/rhythmbox/plugins/lastfm_queue/lastfm_queue.py", line 76, in do_activate shell.set_data('LastFmDynamicPluginInfo', data)
File "/usr/lib/python2.7/dist-packages/gi/overrides/GObject.py", line 555, in _unsupported_data_method
    raise RuntimeError('Data access methods are unsupported. '
RuntimeError: Data access methods are unsupported. Use normal Python attributes instead
```

Any idea ?

Thanks for your work

**Comment by asermax** [comment]
This probably haves to do with the backward incompatible changes made on Rhytmbox 2.99. Please read [this other issue](https://github.com/fossfreedom/coverart-browser/issues/171) on another plugin I'm working on where this change is lengthy explained.

Currently the owner of that repo is working on a compatibility layer to solve this kind of issues.
I will give a more closer look at the error you posted when I have a little more of time during the week (the biggest problem is that I don't have that version of rhytmbox so I need to put togheter a VM u_u).

**Comment by fossfreedom** [comment]
@asermax - in ubuntu 13.04 - "stock rhythmbox" is RBv2.98 - so, unless the OP has added the Gnome 3.8 PPA which would have installed RBv2.99 - this is another issue.

Looking at the error message - maybe its a change in the newer version of pygobject available in Fedora 19/Ubuntu 13.04 than compared to Debian Wheezy/Ubuntu 12.10.

Possiby the "set_data" syntax is not valid - I dont see this here (http://www.roojs.com/seed/gir-1.2-gtk-3.0/seed/RB.Shell.html) - so maybe it was a deprecated syntax that has finally been removed in pygobject?

Anyway - all of the above is probably a guess :)

**Comment by asermax** [comment]
Ow, thought it was related to the changes on 2.99 since you redirected a [similar issue](https://github.com/fossfreedom/radio-browser/issues/3) (same Ubuntu version) to the menu changes issue.

Either way, I will change the related code to use attributes instead of `set_data` and hope it fixes the problem xD

**Comment by fossfreedom** [comment]
The "big" problem with Ubuntu is the Personal Packaging Archives (PPA's) - people add these to get the "newest" stuff - in https://github.com/fossfreedom/radio-browser/issues/3 - the OP added the Gnome 3.8 PPA on-top-of Ubuntu 13.10.  This PPA comes with RB2.99

Confusing?  Yes - I see this all the time on AskUbuntu Stack Exchange.  It gets worse during the 6 month cycle between main releases - all sorts of PPA's get created and you get very different versions of apps being installed that were not in the original release.

**Comment by asermax** [comment]
Lol, yeah, PPA are kinda confusing if you are not used to APT. I have some PPA's installed myself (yeah, on Debian d: but I make sure the packages are compatible!), but always with pin priorities to keep APT from updating stuff that it shouldn't :<

Anyway, back in topic: I modified the bits that used the `set_data` and `get_data` methods. Luckily nothing got broken and it should work for Ubuntu 13.04 now.
@lilley please update your plugin copy with this repo's master branch and let me know if it fixed it for you :+1:

**Comment by NicolasEhrhardt** [comment]
Hi guys,

I confirm that I have the 2.98 version.
And that your fix worked !

Thanks  :+1: !

**Comment by asermax** [comment]
nicey, glad to hear that it worked :]
